name: Publish 🚀

on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build Flow
    runs-on: ubuntu-latest

    steps: 
      - name: Run Composite Action 
      - uses: .github/build@v1
        with:
          solution-file: 'PokemonReview.sln'
          configuration: 'Release'
          name: ${{ github.event.input.name }}
