name: Publish 🚀

on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build Flow
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      
      - name: Run Composite Action 
        uses: ./.github/build
        with:
          solution-file: 'PokemonReview.sln'
          configuration: 'Release'
          name: ${{ github.event.input.name }}
