name: Publish 🚀

on:
  workflow_dispatch: 
    inputs:
      name: 
        description: name to greet
        type: string
        required: true

jobs:
  build:
    name: Build Flow
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      
      - name: Run Composite Action 
        uses: ./actions/build
        with:
          solution-file: 'PokemonReview.sln'
          configuration: 'Release'
          name: ${{ github.event.input.name }}

  deploy-job:
    needs: [build]
    uses: Anubhavdevv/PokemonReviewApp/.github/workflows/deploy.yml@main
    with:
      name: ${{ inputs.name }}
        
